In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3],[1,2,3]])
print(a)

[[1 2 3]
 [1 2 3]]


In [41]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a = np.linspace(2,5,num=5)
a

array([2.  , 2.75, 3.5 , 4.25, 5.  ])

In [43]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
a = np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [45]:
a = np.diag([1,2,3],2)
a

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 3],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [46]:
a = np.vander((1,2,3,4),4)
a

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [47]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [48]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [49]:
a = np.random.default_rng(42).random((2,3))
a

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235]])

In [50]:
a = np.indices((3,3,3))
a

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]]],


       [[[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2]],

        [[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2]],

        [[0, 0, 0],
         [1, 1, 1],
         [2, 2, 2]]],


       [[[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]]]])

In [51]:
a = np.array([1,2,3,4])
b = a[:2]
b+=1
b

array([2, 3])

In [59]:
a = np.ones((2,2))
b = np.diag((2,2),0)
c = np.eye(2,2)
d = np.zeros((2,2))
x = np.block([[a,b],[c,d]])

In [56]:
x

array([[1., 1., 2., 0.],
       [1., 1., 0., 2.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [61]:
x = np.vstack((a,b))
x

array([[1., 1.],
       [1., 1.],
       [2., 0.],
       [0., 2.]])

In [62]:
x = np.hstack((a,b))
x

array([[1., 1., 2., 0.],
       [1., 1., 0., 2.]])

In [70]:
with open('merge.txt','r') as f:
    print(f.read())

name,year,field

steve,2001,IT
harrington,2001,IT



In [71]:
np.genfromtxt("merge.txt",delimiter=",",usemask=True)

masked_array(
  data=[[nan, nan, nan],
        [nan, 2001.0, nan],
        [nan, 2001.0, nan]],
  mask=[[False, False, False],
        [False, False, False],
        [False, False, False]],
  fill_value=1e+20)

In [72]:
np.genfromtxt("merge.txt",delimiter=",")

array([[  nan,   nan,   nan],
       [  nan, 2001.,   nan],
       [  nan, 2001.,   nan]])

In [73]:
np.genfromtxt("merge.txt",delimiter=",",filling_values=50)

array([[  50.,   50.,   50.],
       [  50., 2001.,   50.],
       [  50., 2001.,   50.]])

In [75]:
np.genfromtxt("merge.txt",delimiter=",",filling_values=99,dtype = 'int8')

array([[ 99,  99,  99],
       [ 99, -47,  99],
       [ 99, -47,  99]], dtype=int8)

In [82]:
np.genfromtxt("merge.txt",delimiter=2)

ValueError: Some errors were detected !
    Line #3 (got 7 columns instead of 8)
    Line #4 (got 9 columns instead of 8)

In [63]:
import csv

In [67]:
with open("merge.txt",'w') as csvfile:
    w=csv.writer(csvfile)
    w.writerow(["name","year","field"])

In [68]:
with open("merge.txt",'a',newline='') as csvfile:
    wr=csv.writer(csvfile)
    wr.writerow(["steve","2001","IT"])

In [69]:
with open("merge.txt",'a',newline='') as csvfile:
    wr=csv.writer(csvfile)
    wr.writerow(["harrington","2001","IT"])